import React from "react";
import Head from "next/head";
import Foi from "@/components/Foi/Foi";
import Layout from "@/Layout/Layout";

function foi() {
  return (
    <>
      <Head>
        <title>Future Open Interest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Foi />
      </Layout>
    </>
  );
}

export default foi;
