import React from "react";
import Head from "next/head";
import Layout from "@/Layout/Layout";
import Dashboard from "@/components/DashBoard/Dashboard";

function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboard />
      </Layout>
    </>
  );
}

export default Home;
